apiVersion: apps/v1
kind: Deployment
metadata:
  name:  moderations-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderations
  template:
    metadata:
      labels:
        app: moderations
    spec:
      containers:
        - name: moderations
          image: willycedric/ms-moderations:latest

---
apiVersion: v1
kind: Service
metadata:
  name: moderations-clusterip-srv
spec:
  selector:
    app: moderations
  type: ClusterIP
  ports:
    - name: moderations
      protocol: TCP
      port: 4003
      targetPort: 4003